import { isSupabaseConfigured, supabase } from "@/lib/supabase";

export type StudentCvAnalysis = {
  extracted_skills: string[];
  suggested_roles: string[];
  strengths: string[];
  weaknesses: string[];
  improvement_suggestions: string[];
  overall_score: number | null;
  created_at: string;
  updated_at: string;
};

type Resource = { title: string; url: string; type?: "Technical" | "Soft Skill"; level?: "Beginner" | "Intermediate" | "Advanced"; cost?: "Free" | "Paid" };
type DomainTemplate = { domain: string; keywords: string[]; requiredSkills: string[]; roles: string[]; resources: Resource[] };

const safe = (v: unknown): string[] => (Array.isArray(v) ? v.filter((x): x is string => typeof x === "string") : []);
const l = (v: string) => v.toLowerCase();

const DOMAIN_TEMPLATES: DomainTemplate[] = [
  { domain: "Software / Computer Engineering / Web Development", keywords: ["software","computer engineering","computer science","developer","react","javascript","typescript","node","backend","frontend","full stack","api","git","sql","database"], requiredSkills: ["JavaScript","TypeScript","React","Node.js","REST API","SQL","Git","Testing","HTML","CSS"], roles: ["Software Developer Intern","Frontend Intern","Backend Intern","Full Stack Intern","Web Developer Intern"], resources: [{ title: "freeCodeCamp", url: "https://www.freecodecamp.org/learn/", type: "Technical", level: "Beginner", cost: "Free" }, { title: "MDN Learn", url: "https://developer.mozilla.org/en-US/docs/Learn", type: "Technical", level: "Beginner", cost: "Free" }, { title: "React Learn", url: "https://react.dev/learn", type: "Technical", level: "Beginner", cost: "Free" }, { title: "Node.js Learn", url: "https://nodejs.org/en/learn", type: "Technical", level: "Beginner", cost: "Free" }, { title: "SQLBolt", url: "https://sqlbolt.com/", type: "Technical", level: "Beginner", cost: "Free" }] },
  { domain: "Data Science / AI / Statistics / Analytics", keywords: ["data science","artificial intelligence","machine learning","python","pandas","numpy","statistics","power bi","tableau","sql","analytics","model"], requiredSkills: ["Python","SQL","Pandas","NumPy","Statistics","Machine Learning","Data Visualization","Power BI/Tableau","scikit-learn"], roles: ["Data Analyst Intern","Data Science Intern","AI Intern","Machine Learning Intern","BI Intern"], resources: [{ title: "Kaggle Learn", url: "https://www.kaggle.com/learn", type: "Technical", level: "Beginner", cost: "Free" }, { title: "Google ML Crash Course", url: "https://developers.google.com/machine-learning/crash-course", type: "Technical", level: "Beginner", cost: "Free" }, { title: "scikit-learn tutorials", url: "https://scikit-learn.org/stable/tutorial/index.html", type: "Technical", level: "Beginner", cost: "Free" }, { title: "Mode SQL Tutorial", url: "https://mode.com/sql-tutorial/", type: "Technical", level: "Beginner", cost: "Free" }] },
  { domain: "Chemical Engineering / Chemistry / Process / R&D", keywords: ["chemical engineering","chemistry","process","laboratory","r&d","quality control","hplc","ftir","aspen","matlab","gmp","validation","thermodynamics","distillation"], requiredSkills: ["Process Engineering","Quality Control","R&D","Aspen Plus","MATLAB","HPLC","FTIR","Process Validation","GMP","Data Analysis","Laboratory Safety"], roles: ["R&D Intern","Process Engineering Intern","Quality Control Intern","Laboratory Intern","Production Intern"], resources: [{ title: "MIT OCW", url: "https://ocw.mit.edu/", type: "Technical", level: "Beginner", cost: "Free" }, { title: "AspenTech University", url: "https://www.aspentech.com/en/aspentech-university", type: "Technical", level: "Beginner", cost: "Free" }, { title: "FDA cGMP basics", url: "https://www.fda.gov/drugs/pharmaceutical-quality-resources/facts-about-current-good-manufacturing-practices-cgmps", type: "Technical", level: "Beginner", cost: "Free" }] },
  { domain: "Mechanical Engineering", keywords: ["mechanical engineering","solidworks","cad","ansys","manufacturing","thermodynamics","fluid mechanics","mechanics","machine design","production"], requiredSkills: ["CAD","SolidWorks","ANSYS","Technical Drawing","Manufacturing","Thermodynamics","Fluid Mechanics","Machine Design","MATLAB"], roles: ["Mechanical Design Intern","Manufacturing Intern","R&D Engineering Intern","Production Intern"], resources: [{ title: "MIT OCW", url: "https://ocw.mit.edu/" }, { title: "ANSYS Learning", url: "https://www.ansys.com/academic/learning-resources" }] },
  { domain: "Electrical / Electronics Engineering", keywords: ["electrical engineering","electronics","circuit","embedded","pcb","arduino","stm32","fpga","control systems","power electronics","signal processing"], requiredSkills: ["Circuit Analysis","PCB Design","Embedded Systems","C/C++","MATLAB","Simulink","Control Systems","Power Electronics","Signal Processing"], roles: ["Electronics Intern","Embedded Systems Intern","Hardware Intern","Control Systems Intern"], resources: [{ title: "All About Circuits", url: "https://www.allaboutcircuits.com/textbook/" }, { title: "Arduino Docs", url: "https://docs.arduino.cc/" }] },
  { domain: "Industrial Engineering / Operations / Supply Chain", keywords: ["industrial engineering","operations research","optimization","supply chain","production planning","scheduling","lean","six sigma","forecasting","inventory"], requiredSkills: ["Operations Research","Optimization","Supply Chain","Production Planning","Forecasting","Lean","Six Sigma","Excel","Python","KPI"], roles: ["Operations Intern","Supply Chain Intern","Planning Intern","Process Improvement Intern"], resources: [{ title: "MIT OCW", url: "https://ocw.mit.edu/" }, { title: "Lean Six Sigma", url: "https://www.coursera.org/learn/six-sigma-principles" }] },
  { domain: "Civil Engineering / Architecture / Construction", keywords: ["civil engineering","construction","structural","autocad","revit","bim","project management","geotechnical","transportation","architecture"], requiredSkills: ["AutoCAD","Revit","BIM","Structural Analysis","Construction Management","Project Planning","Technical Drawing","Site Safety"], roles: ["Site Engineer Intern","Structural Engineering Intern","BIM Intern","Construction Management Intern"], resources: [{ title: "Autodesk Learn", url: "https://www.autodesk.com/learning" }] },
  { domain: "Environmental Engineering / Sustainability / Energy", keywords: ["environmental engineering","sustainability","renewable energy","water treatment","wastewater","carbon footprint","esg","energy efficiency","climate"], requiredSkills: ["Sustainability","Environmental Impact","Water/Wastewater Treatment","Carbon Footprint","ESG Reporting","Renewable Energy","Data Analysis"], roles: ["Sustainability Intern","Environmental Engineering Intern","Energy Intern","ESG Intern"], resources: [{ title: "UN resources", url: "https://www.un.org/en/our-work" }] },
  { domain: "Biomedical Engineering / Biotechnology / Life Sciences", keywords: ["biomedical engineering","biotechnology","biology","molecular biology","cell culture","medical devices","clinical","bioinformatics","lab"], requiredSkills: ["Laboratory Techniques","Data Analysis","Biomedical Devices","Biology","Quality Systems","Regulatory Awareness","MATLAB/Python"], roles: ["Biomedical Intern","Biotechnology Intern","Clinical Research Intern","R&D Intern"], resources: [{ title: "PubMed tutorials", url: "https://pubmed.ncbi.nlm.nih.gov/help/" }] },
  { domain: "Materials / Metallurgical Engineering", keywords: ["materials engineering","metallurgy","polymers","composites","ceramics","corrosion","characterization","sem","xrd","mechanical testing"], requiredSkills: ["Materials Characterization","Polymers","Metallurgy","Corrosion","Mechanical Testing","SEM/XRD","Quality Control","Data Analysis"], roles: ["Materials Engineering Intern","Metallurgy Intern","Quality Intern","R&D Intern"], resources: [{ title: "MIT OCW", url: "https://ocw.mit.edu/" }] },
  { domain: "Aerospace / Aeronautical Engineering", keywords: ["aerospace","aeronautical","aircraft","flight","propulsion","aerodynamics","ansys","matlab","cad","control systems"], requiredSkills: ["Aerodynamics","Flight Mechanics","MATLAB","CAD","ANSYS/CFD","Control Systems","Technical Reporting"], roles: ["Aerospace Engineering Intern","Aerodynamics Intern","Design Intern","Simulation Intern"], resources: [{ title: "NASA learning resources", url: "https://www.nasa.gov/learning-resources/" }] },
  { domain: "Mechatronics / Robotics / Automation", keywords: ["mechatronics","robotics","automation","ros","gazebo","control systems","embedded","sensors","actuators","plc","arduino"], requiredSkills: ["ROS","Control Systems","Embedded Systems","Sensors","Actuators","Python/C++","MATLAB","PLC","Simulation"], roles: ["Robotics Intern","Automation Intern","Mechatronics Intern","Control Systems Intern"], resources: [{ title: "ROS documentation", url: "https://docs.ros.org/" }, { title: "Gazebo docs", url: "https://gazebosim.org/docs" }] },
  { domain: "Management Engineering / Business / Strategy", keywords: ["management engineering","business","strategy","operations","product","project management","kpi","stakeholder","market analysis","consulting"], requiredSkills: ["Business Analysis","Strategy","KPI","Excel","Project Management","Market Analysis","Stakeholder Management","Presentation"], roles: ["Business Analyst Intern","Strategy Intern","Project Management Intern","Product Intern"], resources: [{ title: "Google Project Management", url: "https://www.coursera.org/professional-certificates/google-project-management" }, { title: "Atlassian Agile", url: "https://www.atlassian.com/agile" }] },
  { domain: "Finance / Economics / Accounting", keywords: ["finance","economics","accounting","financial analysis","valuation","budget","reporting","excel","investment","risk"], requiredSkills: ["Financial Analysis","Excel","Accounting","Valuation","Budgeting","Reporting","Power BI","SQL","Risk Analysis"], roles: ["Finance Intern","Financial Analyst Intern","Accounting Intern","Risk Intern"], resources: [{ title: "CFI", url: "https://corporatefinanceinstitute.com/resources/" }, { title: "Investopedia", url: "https://www.investopedia.com/" }] },
  { domain: "Marketing / Advertising / Growth / Communication", keywords: ["marketing","advertising","brand","social media","seo","google analytics","campaign","content","communication","pr"], requiredSkills: ["Market Research","SEO","Social Media","Google Analytics","Campaign Management","Copywriting","Excel","Reporting"], roles: ["Marketing Intern","Growth Intern","Brand Intern","Social Media Intern","Communications Intern"], resources: [{ title: "Google Skillshop", url: "https://skillshop.withgoogle.com/" }, { title: "HubSpot Academy", url: "https://academy.hubspot.com/" }] },
  { domain: "Psychology / HR / People Operations", keywords: ["psychology","human resources","recruitment","organizational psychology","counseling","assessment","interview","employee","training"], requiredSkills: ["Interviewing","Recruitment","Communication","Psychological Assessment Awareness","HR Analytics","Excel","Employee Relations","Research Methods"], roles: ["HR Intern","Recruitment Intern","People Operations Intern","Organizational Psychology Intern","Training & Development Intern"], resources: [{ title: "SHRM", url: "https://www.shrm.org/" }, { title: "APA resources", url: "https://www.apa.org/education-career" }] },
  { domain: "Law / Political Science / International Relations", keywords: ["law","legal","political science","international relations","policy","compliance","regulation","contract","research","diplomacy"], requiredSkills: ["Legal Research","Policy Analysis","Compliance","Contract Review","Academic Writing","Research","Communication","Critical Thinking"], roles: ["Legal Intern","Compliance Intern","Policy Research Intern","International Relations Intern"], resources: [{ title: "UN resources", url: "https://www.un.org/en/our-work" }, { title: "EU Learning Corner", url: "https://learning-corner.learning.europa.eu/index_en" }] },
  { domain: "Education / Teaching / Guidance", keywords: ["education","teaching","pedagogy","curriculum","classroom","guidance","learning","tutoring","instructional design"], requiredSkills: ["Lesson Planning","Communication","Curriculum Design","Educational Technology","Assessment","Classroom Management"], roles: ["Teaching Intern","Education Intern","Instructional Design Intern","Guidance Intern"], resources: [{ title: "Khan Academy", url: "https://www.khanacademy.org/" }, { title: "Edutopia", url: "https://www.edutopia.org/" }] },
  { domain: "Media / Journalism / Translation / Languages", keywords: ["journalism","media","translation","english","german","content","writing","editing","copywriting","localization","communication"], requiredSkills: ["Writing","Editing","Translation","Research","Content Strategy","SEO Basics","Communication","Proofreading"], roles: ["Content Intern","Translation Intern","Editorial Intern","Communications Intern"], resources: [{ title: "Purdue OWL", url: "https://owl.purdue.edu/" }] },
  { domain: "Design / UX / Visual Communication", keywords: ["design","ux","ui","figma","user research","wireframe","prototype","visual communication","graphic design","adobe"], requiredSkills: ["Figma","Wireframing","Prototyping","User Research","UI Design","UX Writing","Design Systems","Adobe Tools"], roles: ["UX Intern","UI Designer Intern","Product Design Intern","Graphic Design Intern"], resources: [{ title: "Figma Learn", url: "https://help.figma.com/hc/en-us/categories/360002051613-Learn-design" }, { title: "Nielsen Norman Group", url: "https://www.nngroup.com/articles/" }] },
  { domain: "Health Sciences / Nursing / Medicine-related", keywords: ["health","nursing","medicine","clinical","patient","public health","medical","hospital","epidemiology","healthcare"], requiredSkills: ["Clinical Awareness","Patient Communication","Research Methods","Data Analysis","Healthcare Quality","Ethics","Public Health"], roles: ["Clinical Intern","Public Health Intern","Healthcare Operations Intern","Research Intern"], resources: [{ title: "WHO resources", url: "https://www.who.int/" }, { title: "CDC training", url: "https://www.cdc.gov/training/" }] },
  { domain: "General / Early Career", keywords: [], requiredSkills: ["Communication","Excel","Research","Presentation","Teamwork","Time Management","Problem Solving","Reporting"], roles: ["General Intern","Project Intern","Operations Intern","Research Intern"], resources: [{ title: "Career Success", url: "https://www.coursera.org/learn/career-success", type: "Soft Skill", level: "Beginner", cost: "Free" }, { title: "Google Digital Garage", url: "https://learndigital.withgoogle.com/digitalgarage", type: "Soft Skill", level: "Beginner", cost: "Free" }, { title: "Microsoft Excel Support", url: "https://support.microsoft.com/excel", type: "Technical", level: "Beginner", cost: "Free" }] },
];

export const getCurrentStudentId = async (): Promise<string | null> => { /*...*/
  if (!isSupabaseConfigured || !supabase) return null;
  const { data: au } = await supabase.auth.getUser(); if (!au.user) return null;
  const { data: p } = await supabase.from("persons").select("person_id").eq("auth_user_id", au.user.id).maybeSingle(); if (!p?.person_id) return null;
  const { data: s } = await supabase.from("students").select("student_id").eq("person_id", p.person_id).maybeSingle();
  return s?.student_id ?? null;
};

export const getLatestStudentCvAnalysis = async (): Promise<StudentCvAnalysis | null> => {
  const studentId = await getCurrentStudentId(); if (!studentId || !supabase) return null;
  const { data } = await supabase.from("cv_analysis_reports").select("extracted_skills,suggested_roles,strengths,weaknesses,improvement_suggestions,overall_score,created_at,updated_at").eq("student_id", studentId).eq("analysis_status", "completed").order("created_at", { ascending: false }).limit(1).maybeSingle();
  if (!data) return null;
  return { extracted_skills: safe(data.extracted_skills), suggested_roles: safe(data.suggested_roles), strengths: safe(data.strengths), weaknesses: safe(data.weaknesses), improvement_suggestions: safe(data.improvement_suggestions), overall_score: typeof data.overall_score === "number" ? data.overall_score : null, created_at: data.created_at ?? "", updated_at: data.updated_at ?? "" };
};

export const detectStudentDomain = (analysis: StudentCvAnalysis | null) => {
  const pool = [ ...safe(analysis?.extracted_skills), ...safe(analysis?.suggested_roles), ...safe(analysis?.strengths), ...safe(analysis?.weaknesses), ...safe(analysis?.improvement_suggestions)].map(l).join(" ");
  const scores = DOMAIN_TEMPLATES.map(d => ({ d, matched: d.keywords.filter(k => pool.includes(l(k))), score: d.keywords.filter(k => pool.includes(l(k))).length }));
  scores.sort((a,b)=>b.score-a.score);
  const top = scores[0]; const second = scores[1];
  let domain = top?.score ? top.d.domain : "General / Early Career";
  if (top && second && top.score>0 && second.score>0 && top.score-second.score<=1) {
    if ((top.d.domain.includes("Software") && second.d.domain.includes("Data")) || (second.d.domain.includes("Software") && top.d.domain.includes("Data"))) domain = "Software + Data/AI";
    else if ((top.d.domain.includes("Chemical") && second.d.domain.includes("Management")) || (second.d.domain.includes("Chemical") && top.d.domain.includes("Management"))) domain = "Chemical / Process + Business Operations";
    else if ((top.d.domain.includes("Psychology") && second.d.domain.includes("Psychology")) || top.d.domain.includes("Psychology") || second.d.domain.includes("Psychology")) domain = "Psychology / People Operations";
    else domain = `${top.d.domain} + ${second.d.domain}`;
  }
  const confidence = Math.min(98, top?.score ? 45 + top.score * 10 : 40);
  return { domain, confidence, matchedKeywords: top?.matched ?? [], suggestedRoles: analysis?.suggested_roles ?? [] };
};

export const getDomainSkillTemplate = (domain: string) => DOMAIN_TEMPLATES.find(d => d.domain === domain) ?? DOMAIN_TEMPLATES[DOMAIN_TEMPLATES.length - 1];

export const generateSkillGaps = (analysis: StudentCvAnalysis | null) => {
  const det = detectStudentDomain(analysis); const template = getDomainSkillTemplate(det.domain);
  const have = new Set(safe(analysis?.extracted_skills).map(l));
  const gaps = template.requiredSkills.filter(s => !have.has(l(s))).slice(0,8).map((skill,i)=>({ skill, currentLevel: Math.max(1, 3-i%3), targetLevel: 4, urgency: i<3?"High":i<6?"Medium":"Low", reason: safe(analysis?.weaknesses)[0] || `This is frequently required in ${det.domain}.`, relatedRoles: template.roles.slice(0,3), resources: template.resources.slice(0,3) }));
  return gaps.length ? gaps : template.requiredSkills.slice(0,3).map(skill=>({ skill,currentLevel:2,targetLevel:4,urgency:"Medium",reason:"Foundation building.",relatedRoles:template.roles.slice(0,2),resources:template.resources.slice(0,2)}));
};

export const generateLearningPath = (analysis: StudentCvAnalysis | null) => {
  const det = detectStudentDomain(analysis); const template = getDomainSkillTemplate(det.domain); const gaps = generateSkillGaps(analysis);
  const resources = [...template.resources, ...getDomainSkillTemplate("General / Early Career").resources].slice(0,12).map((r, idx)=>({ id:`res-${idx}-${r.title}`, ...r, skill: gaps[idx % gaps.length]?.skill ?? template.requiredSkills[0] }));
  return { domain: det.domain, resources, roadmap: { week: resources.slice(0,3), month: resources.slice(3,7), quarter: resources.slice(7,12) } };
};
export const generateProjectSuggestions = (analysis: StudentCvAnalysis | null) => generateSkillGaps(analysis).slice(0,4).map((g, i) => `${i + 1}. Build a portfolio project that demonstrates ${g.skill} for ${g.relatedRoles[0]}.`);
export const generateInterviewPreparation = (analysis: StudentCvAnalysis | null) => generateSkillGaps(analysis).slice(0,4).map((g) => `Prepare STAR examples for ${g.skill} and explain how you improved it.`);
export const generateNotifications = (analysis: StudentCvAnalysis | null) => {
  if (!analysis) return [{ id: "onboarding", type: "cv improvement reminder", title: "Upload and analyze your CV", message: "Complete onboarding to unlock personalized insights.", link: "/onboarding" }];
  const det = detectStudentDomain(analysis); const gap = generateSkillGaps(analysis)[0];
  return [
    { id: "gap", type: "skill gap alert", title: `${gap.skill} needs attention`, message: gap.reason, link: "/skill-gap" },
    { id: "learn", type: "learning recommendation", title: `Start your ${det.domain} learning path`, message: "Your roadmap is ready.", link: "/learning-path" },
    { id: "role", type: "suggested role insight", title: "Suggested roles updated", message: (analysis.suggested_roles[0] ?? "General Intern") + " is a strong next step.", link: "/profile" },
    { id: "cv", type: "cv improvement reminder", title: "Improve your CV clarity", message: analysis.improvement_suggestions[0] ?? "Add measurable achievements.", link: "/profile" },
    { id: "project", type: "project suggestion", title: "New project idea", message: generateProjectSuggestions(analysis)[0], link: "/profile" },
    { id: "interview", type: "interview preparation reminder", title: "Interview prep task", message: generateInterviewPreparation(analysis)[0], link: "/learning-path" },
  ];
};
export const generateProfileInsights = (analysis: StudentCvAnalysis | null) => ({ domain: detectStudentDomain(analysis), skillGaps: generateSkillGaps(analysis), projects: generateProjectSuggestions(analysis), interviewPrep: generateInterviewPreparation(analysis) });
